### ISSUE TITLE
Freezing the program when scrolling

### ISSUE THREAD

**Issue by dd194** [LNReader/lnreader-sources#111]
### Source information

Any source with more than 150-200 chapters

### Steps to reproduce

When scrolling, there are freezes of the program, it concerns heavy works with more than 150 chapters.  Try to check on any great piece, such as the Legendary Moonlight Sculptor

### Expected behavior

https://drive.google.com/file/d/1QTtyMJOrL7hODzPbErFxIxrsriwdni2h/view?usp=drivesdk

### Actual behavior

Took a screenshot, link above.  If you have problems with the video, write on the server in discord, my nickname is @Darik#2844

### LNReader version

1.1.7

### Android version

11

### Other details

Device Poco X3 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.6](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> In order to constrain memory and enable smooth scrolling, content is rendered asynchronously offscreen. This means it's possible to scroll faster than the fill rate and momentarily see blank content. This is a tradeoff that can be adjusted to suit the needs of each application, and we are working on improving it behind the scenes.

This is a React Native issue. You can read about it [here.](https://reactnative.dev/docs/flatlistl)
