### ISSUE TITLE
KolNovel And RewayatAr : Does not open

### ISSUE THREAD

**Issue by hani1998** [LNReader/lnreader-sources#118]
### Source information

KolNovel , RewayatAr

### Steps to reproduce

1- Go to the source
2 - open source

### Expected behavior

should open

### Actual behavior

Did not open there was an error

### LNReader version

1.1.7

### Android version

Android 10

### Other details

These are images of the source from the application
![Screenshot_20211108-074009](https://user-images.githubusercontent.com/90999286/140685753-e2ef1fe7-d0e4-4aab-8b1a-4319d4f41a6f.png)
![Screenshot_20211108-074002](https://user-images.githubusercontent.com/90999286/140685756-b298db21-0b82-46e6-a47e-9a84e101b4a0.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.6](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
RewayatAr has cloudflare protection and KolNovel has some other scraping protection service which currently the app cannot bypass.
