### ISSUE TITLE
[Bug] Error with retrieving novels from some sources

### ISSUE THREAD

**Issue by k5924** [LNReader/lnreader-sources#133]
### Source information

LightNovelPub

### Steps to reproduce

Scenario 1: Refreshing library:
1. Pull to refresh library

Scenario 2: searching for novel in global search:
1. Search for novel_name in global search section

### Expected behavior

On library refresh:
1. Toast message says updating
2. Notified that update is complete

On global search:
1. Novel is searched for in all sources
2. If novel exists display novel else show no results

### Actual behavior

On library refresh:
1. Toast message says updating library
2. All toast messages from LightNovelPub says "novel_name: cannot convert null value to object" where novel_name is the actual name of the novel in my library

On global search:
1. Searches for novel
2. Displays "JSON Parse error: Unexpected token: <" in red text

### LNReader version

1.1.7

### Android version

Android 11

### Other details

All other sources appear to be working except some sources like LNMTL displaying "Cannot convert null value to object" when searching for a novel in global search.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.6](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by k5924** [comment]
The webview behaviour is similar for LightNovelPub as looking at the webview, there are new chapters but I think the error where it cant convert a null value to object stops the new chapters from being loaded/added to the novel in the app

**Comment by Kai-Nui** [comment]
Foxaholic doesn't connect properly whether in global search or browsing. Also, links in NovelUpdates that redirect to foxaholic show Cloudflare browser check message instead of actual chapter text.

**Comment by k5924** [comment]
I tried to webscrape the page in Python and it looks like cloudflare is displaying a captcha that needs to be solved before the actual page is displayed.
