### ISSUE TITLE
[Bug] Can't read novels from TravisTranslation extension

### ISSUE THREAD

**Issue by seizue** [LNReader/lnreader-sources#139]
Can't read novels from TravisTranslation extension. It says JSON Parse error 
![Screenshot_2021-12-23-12-59-49-29](https://user-images.githubusercontent.com/25120376/147190668-8906c672-8cb5-4832-87cc-a09076fab28d.jpg)

**Comment by Kai-Nui** [comment]
This is similar to LightNovelPub error. https://github.com/LNReader/lnreader-sources/issues/133
