### ISSUE TITLE
Scribble hub : No results found 

### ISSUE THREAD

**Issue by THElegend5** [LNReader/lnreader-sources#152]
### Source information

Scribble Hub

### Steps to reproduce

1. Locate the scribble hub source.
2. Tap the browse button.

### Expected behavior

Novels are shown.

### Actual behavior

Shows no results found.

### LNReader version

1.1.8

### Android version

Android 11

### Other details

Webview works fine.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.6](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
ScribbleHub is working fine for me.

**Comment by THElegend5** [comment]
Somehow it started working for me too.
