### ISSUE TITLE
Arnovel (No Result Found)

### ISSUE THREAD

**Issue by IslamAbdel** [LNReader/lnreader-sources#164]
### Source information

Arnovel

### Steps to reproduce

1.open extinction 
2. It doesn't open 
3. It's say no result found 

### Expected behavior

It should open 

### Actual behavior

This happens instead ..
![Screenshot_2022-01-30-17-17-48-195_com rajarsheechatterjee LNReader](https://user-images.githubusercontent.com/93197738/151705709-ec39b5ec-ea31-4951-95f8-f083512c9068.jpg)

### LNReader version

1.1.8

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.6](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Works fine for me. If the issue is still there reopen this.

![Screenshot_20220318-102333.jpg](https://user-images.githubusercontent.com/57822170/158939910-2db55dd3-9a56-4bac-a68b-59843120ceb4.jpg)
