### ISSUE TITLE
Riwayt

### ISSUE THREAD

**Issue by louay4585** [LNReader/lnreader-sources#171]
### Source name

Eiwaut

### Source link

riwayt.com

### Language

Arabic

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
the site is not alive.
if you mean `riwyat.com`, it was implemented
