### ISSUE TITLE
Anilist

### ISSUE THREAD

**Issue by OshekharO** [LNReader/lnreader-sources#179]
### Source name

Anilist

### Source link

https://anilist.co

### Language

English

### Other details

Please Add this Instead Of MyAnimeList.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
You mean add Anilist in Discover in Browse tab?

**Comment by discordiy** [comment]
> You mean add Anilist in Discover in Browse tab?

Yes.

**Comment by karmakarmeghdip** [comment]
I second it! Don't have any MAL account, anilist only, gotta track those LNs in my library.....
