### ISSUE TITLE
Ranobelib: Images are not displayed 

### ISSUE THREAD

**Issue by AceHardwareGOK** [LNReader/lnreader-sources#181]
There are no images in ranobelib
![IMG_20220219_035530](https://user-images.githubusercontent.com/63394217/154781885-b93d7c56-8d37-44aa-b344-36e5bfcb866a.jpg)

**Comment by rajarsheechatterjee** [comment]
Novel and chapter name?

**Comment by AceHardwareGOK** [comment]
> Novel and chapter name?

Novel: Classroom of the Elite, any chapter (e.g. https://ranobelib.me/youkoso-jitsuryoku-shijou-shugi-no-kyoushitsu-e-novel/v21/c0.3)

**Comment by rajarsheechatterjee** [comment]
Fixed in LNReader/lnreader@2d85fa09383824c3cb07a38ebe4848ecc73d6998
