### ISSUE TITLE
Novel4up

### ISSUE THREAD

**Issue by yemenihandsome** [LNReader/lnreader-sources#183]
### Source name

Novel4up

### Source link

https://novel4up.com

### Language

Arabic

### Other details

We hope to add  😊

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Already added in LNReader/lnreader@5f3959d62d27380ef2fd863f0a0da6b8769ca1aa
