### ISSUE TITLE
MyLoveNovel shows "cannot read property 'push' of undefined"

### ISSUE THREAD

**Issue by Kai-Nui** [LNReader/lnreader-sources#192]
### Source information

MyLoveNovel

### Steps to reproduce

1.Go to library or updates tab and pull down to update.
2.Wait until the app fetches data for a novel sourced from MyLoveNovel

### Expected behavior

Should updates novels and the only prompt should be "Library updated"

### Actual behavior

Toast notification showing
"cannot read property "push" of undefined"

### LNReader version

1.1.8

### Android version

Android 8.1

### Other details

![Screenshot_2022-04-02-09-45-00-0002738727~2](https://user-images.githubusercontent.com/96187646/161361124-546982d3-0c6d-4166-ba34-d554540ed6df.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.8](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Kai-Nui** [comment]
Browse works fine when searching novels but once a novel is picked a toast notification saying cannot read property 'push'of undefined also shows up when fetching metadata

**Comment by rajarsheechatterjee** [comment]
They have updated their website's url to https://www.novelhold.com/, so the source is broken.

**Comment by Kai-Nui** [comment]
Oh. I understand. I guess migrating the novels will be the only workaround.
