### ISSUE TITLE
LightNovelPub sourced novels prompt "Network request failed"

### ISSUE THREAD

**Issue by Kai-Nui** [LNReader/lnreader-sources#193]
### Source information

LightNovelPub

### Steps to reproduce

1.Go to library or updates tab and pull down to get updates. 
2. Wait until app fetches data for novel sourced from LightNovelPub

### Expected behavior

Should update novel

### Actual behavior

Toast notification saying "Network request failed" shows up instead

### LNReader version

1.1.8.2

### Android version

8.1

### Other details

![Screenshot_2022-04-02-10-00-19-0170093854~2](https://user-images.githubusercontent.com/96187646/161361491-1f5b622c-c102-4914-9ad0-b8b26c1b288a.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.8](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Kai-Nui** [comment]
Only happens to novels added from LightNovelPub before installing latest update. Novels added after 1.1.8 works fine. Searching for novel within the Browse tab doesn't work though as the novela shown during search are just the few novels on the first page fetched when opening the source.

**Comment by rajarsheechatterjee** [comment]
This happens when the LightNovelPub enables Cloudflare protection. The app cannot bypass it so it gives `Network request failed` on updating or opening the source in browse tab. The source will start working normally once they remove it.
