### ISSUE TITLE
NovelRingan not show cover image

### ISSUE THREAD

**Issue by AhmadNaruto** [LNReader/lnreader-sources#209]
### Source information

https://github.com/LNReader/lnreader/blob/main/src/sources/id/novelringan.js

### Steps to reproduce

open source in app

### Expected behavior

showing cover image

### Actual behavior

not show cover image

### LNReader version

1.1.8

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.8](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
How is the app supposed to show the cover images if the website does't have them?

**Comment by AhmadNaruto** [comment]
![Screenshot_20220429_094401](https://user-images.githubusercontent.com/47007634/165873306-9eccbd1a-0b95-47f5-954b-f714145eda97.jpg)
they have a cover image..

**Comment by rajarsheechatterjee** [comment]
The covers don't load for me. I'll still look into it.

<img width="1680" alt="Screenshot 2022-05-02 at 3 30 15 PM" src="https://user-images.githubusercontent.com/57822170/166217406-27f4544b-afe1-412b-9103-161c58587f5b.png">
