### ISSUE TITLE
[Source Request] https://mtlnovel.club/

### ISSUE THREAD

**Issue by seizue** [LNReader/lnreader-sources#223]
### Source name

MTLNovel.club

### Source link

https://mtlnovel.club/

### Language

English

### Other details

Finally found an alternative to mtlnation. 
Please add it. 🙏

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
You can download the APK of the app version which has this source from Artifacts section [here](https://github.com/LNReader/lnreader/actions/runs/2282745651).

**Comment by seizue** [comment]
Thank you. It works tho the 'browse' don't appear the novels but in searching, its fine 👍🏻

**Comment by rajarsheechatterjee** [comment]
For Madara sources the app scrapes novels ordered by [rating](https://mtlnovel.club/?m_orderby=rating) which seems to be empty for this website. 

I'll just add an option to override default sort order which will fix this.
