### ISSUE TITLE
Problem in reaperscans

### ISSUE THREAD

**Issue by MazenMohamed909** [LNReader/lnreader-sources#224]
![Screenshot_2022-05-08-02-31-35-557_com rajarsheechatterjee LNReader](https://user-images.githubusercontent.com/105135170/167276859-da1b9d36-2d55-49ca-a437-0c8945b9106f.jpg)
There's some missing novels in there, when I search for novels, the manhwa list appear too.

**Comment by rajarsheechatterjee** [comment]
> There's some missing novels in there

Novels don't seem to be missing, do you mean covers?


> when I search for novels, the manhwa list appear too.

Is there a way to filter the search result by novels in search on their website?

**Comment by MazenMohamed909** [comment]
> novels don't seem to be missing
![Screenshot_2022-05-08-03-55-18-811_com rajarsheechatterjee LNReader](https://user-images.githubusercontent.com/105135170/167278532-6f255dfe-d3da-4b76-b36d-7eba03778182.jpg)
![Screenshot_2022-05-08-03-55-20-704_com rajarsheechatterjee LNReader](https://user-images.githubusercontent.com/105135170/167278535-a6288163-d19a-4895-82b4-498d682d8ce9.jpg)
Only these novels appear for me

> > when I search for novels, the manhwa list appear too.
> 
> Is there a way to filter the search result by novels in search on their website?

![Uploading Screenshot_2022-05-08-03-58-39-802_com.hsv.freeadblockerbrowser.jpg…]()
Yes
