### ISSUE TITLE
Here is the list of all non working sources

### ISSUE THREAD

**Issue by Pheonix-Flames** [LNReader/lnreader-sources#317]
### Source information

readwn.com

### Steps to reproduce

Click on Readwn in Sources it will show 'no results found'

### Expected behavior

It should show Light novels

### Actual behavior

It is showing 'no results found' But when we open it through web browser icon it is working

### LNReader version

1.1.10

### Android version

Android 11

### Other details

Here is a list of all non working Sources but they are working in browser 

ComradeMao
FastNovel
KissLightNovels
LightNovelPub
LightNovelHub
[Ltnovel.com](http://ltnovel.com/)
MTLCornor
NitroScans
Novelmt
NovelPub
NovelsRock
OnlyMTL
Readwn
WebNovelLove
Wuxia.city
WuxiaWorld.cloud

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.10](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Readwn works fine for me (probably something on your end). 

> I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue.

Half of the sources mentioned don't work in webview and the rest are already reported.

**Comment by Pheonix-Flames** [comment]
> issues

Then Remove Those Source which does not work in webview for LNReader
