### ISSUE TITLE
Arnovel: No results / Chapters not working

### ISSUE THREAD

**Issue by louay4585** [LNReader/lnreader-sources#319]
### Source information

Arnovel

### Steps to reproduce

The source don't give any novel 
It says "no results"

### Expected behavior

It should give novels 

### Actual behavior

It doesn't show anything at all 

### LNReader version

1.1.10

### Android version

Android 10

### Other details

Arnovel don't work anymore
PLZ fix it 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.10](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
The source works fine for me. Can you access it in webview?

**Comment by rajarsheechatterjee** [comment]
This is happening because the source website has added Cloudflare protection which the app cannot bypass.
