### ISSUE TITLE
Ar novel websites 

### ISSUE THREAD

**Issue by Guts616** [LNReader/lnreader-sources#323]
Rewayat ar  "not working"

Kol novel. "not working"

+
Please add novel paradise site 

Thanks 🤍

**Comment by rajarsheechatterjee** [comment]
> Rewayat ar "not working"

They changed their domain and their new website (NovelSpace) is already in the app.

> Kol novel. "not working"

Duplicate of #146 

> Please add novel paradise site

Duplicate of #180
