### ISSUE TITLE
ReadNovelFull source novels are empty 

### ISSUE THREAD

**Issue by RougeHero13** [LNReader/lnreader-sources#325]
Novels i downloaded from ReadNovelFull source are empty such as the legendary mechanic, mech touch, 48 hours a day and more.

**Comment by rajarsheechatterjee** [comment]
The source works fine.

Delete the downloaded chapters and check if the chapters have text or not.

**Comment by Nadjahro** [comment]
Just wanted to say that readnovelfull is completely empty
