### ISSUE TITLE
NovelFull.me: Broken

### ISSUE THREAD

**Issue by Enrico-Fabbri** [LNReader/lnreader-sources#326]
The novels which info disappeared are from different sources

![Screenshot_2022-07-10-12-19-43-90_3c1c179116822eec69c21805387f0489.jpg](https://user-images.githubusercontent.com/70634071/178140865-dc917215-beb2-4827-9d65-0f46589d9d86.jpg)![Screenshot_2022-07-10-12-17-15-44_3c1c179116822eec69c21805387f0489.jpg](https://user-images.githubusercontent.com/70634071/178140868-c79670a5-3ee2-4000-ba80-44837620001b.jpg)

**Comment by rajarsheechatterjee** [comment]
Can you share the list of the sources for these novels?

**Comment by Enrico-Fabbri** [comment]
The sources are: 
- NovelFull.me 
- MyLoveNovel

**Comment by rajarsheechatterjee** [comment]
NovelFull.me seems to be broken. 

MyLovelNovel has been fixed in the preview version, you can download it from [here](https://github.com/LNReader/lnreader-preview/releases/tag/v1.1.10.1).

**Comment by Enrico-Fabbri** [comment]
I thought I had also attached this photo but now I realized I didn't 😅

![Screenshot_2022-07-15-22-03-28-46_3c1c179116822eec69c21805387f0489.jpg](https://user-images.githubusercontent.com/70634071/179302592-e8a4ffa4-aecf-4fe2-9014-0da9270dde68.jpg)

**Comment by rajarsheechatterjee** [comment]
NovellFull.me seems to be working fine now. It was probably a source website issue.
