### ISSUE TITLE
Unable to view "The Neighboring Aarya-san who Sometimes Acts Affectionate and Murmuring in Russian" from Novel Updates

### ISSUE THREAD

**Issue by FrederickXTsuna** [LNReader/lnreader-sources#339]
Here to leave a report for "The Neighboring Aarya-san who Sometimes Acts Affectionate and Murmuring in Russian" LN from Novel Updates 

The 1st volume of the LN has an error on the web version, but the 2nd volume of the LN does not

**Comment by rajarsheechatterjee** [comment]
The volume 1 chapter links are outdated on Novel Updates, they return page not found.

![image](https://user-images.githubusercontent.com/57822170/180234913-5dedf686-ad9d-4a4b-b1e9-6f244ec410cf.png)

**Comment by FrederickXTsuna** [comment]
Yes that is for volume 1 of the LN, but volume 2 doesn't have that error
