### ISSUE TITLE
No results found 

### ISSUE THREAD

**Issue by modiabofficial** [LNReader/lnreader-sources#343]
Some sources don't work for example:
1.ArNovel
2.TeamXNovel doesn't work well 
3.KolNovel.

**Comment by rajarsheechatterjee** [comment]
Arnovel and TeamXNovel works fine for me. Maintaining sources of other languages is difficult for me so feel free to fix them or wait for someone to fix them. KolNovel - Duplicate of #146

**Comment by modiabofficial** [comment]
How to fix it?
