### ISSUE TITLE
A small problem that you've already fixed 80% of

### ISSUE THREAD

**Issue by wael-ouni** [LNReader/lnreader-sources#360]
### Source information

Riwyat

### Steps to reproduce

![orca-image--1504834970](https://user-images.githubusercontent.com/111122017/184530273-19d8effc-c9a7-40d0-837a-fe01039b0dab.jpeg)

This is the problem before you fix it 80%. 

![orca-image-857658939](https://user-images.githubusercontent.com/111122017/184530313-fc0c0504-54eb-414c-aad1-7339c83fa1e5.jpeg)

And now this is what it looks like

### Expected behavior

The writing that appears is not from the novel and is not on the site 
![Screenshot_20220814-101719](https://user-images.githubusercontent.com/111122017/184530475-c596cf23-52b7-42c1-aed1-467affb31f9b.jpg)

### Actual behavior

.

### LNReader version

1.1.13

### Android version

8.0.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.10](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
I can't read Arabic so it's difficult for me to fix. Wait for someone to fix this or you could fix it yourself.
