### ISSUE TITLE
[Bug] Doesn't load the Chapters in MTL-NOVEL extension 

### ISSUE THREAD

**Issue by seizue** [LNReader/lnreader-sources#361]
The new extension MTL-NOVEL have a problem. It doesn't load the Chapters. 

![Screenshot_2022-08-15-16-14-41-05](https://user-images.githubusercontent.com/25120376/184600312-3b67dd63-3f0b-4c24-a329-a6c3c6c8722a.jpg)

**Comment by rajarsheechatterjee** [comment]
The chapters aren't loading on the source website also. The issue should be resolved if the source website is fixed.
