### ISSUE TITLE
[Feature request] E-ink support

### ISSUE THREAD

**Issue by James1599** [LNReader/lnreader-sources#364]
I would like to be able to support e-books in the form of taps/gestures to flip "page" without scrolling animation and/or adding a page mode (like in normal book readers), when when you click on the screen flips the whole page at once.

**Comment by rajarsheechatterjee** [comment]
Wrong repository, you should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).

> I would like to be able to support e-books in the form of taps/gestures to flip "page" without scrolling animation and/or adding a page mode (like in normal book readers), when when you click on the screen flips the whole page at once.

Are there any React Native packages which can achieve this behaviour?

**Comment by James1599** [comment]
I apologize for reopening in a knowingly wrong topic, but I'll ask here so as not to multiply queries. You already have a page flip (top-down) via the volume buttons. Isn't it possible/planned to add a tap on the right and left side of the screen as an option for the same functionality?

**Comment by rajarsheechatterjee** [comment]
There's already an [open request](https://github.com/LNReader/lnreader/issues/149) for it. Currently it's not a priority for me, so feel free to contribute and add it yourself.

**Comment by James1599** [comment]
Unfortunately, I'm only a user and not a developer, so I can't add the required function myself, but thank you for the answer.
