### ISSUE TITLE
No Cover Pages on NovelHall Source 

### ISSUE THREAD

**Issue by Pheonix-Flames** [LNReader/lnreader-sources#369]
### Source information

NovelHall

### Steps to reproduce

1. Go To Browse
2. Search 'NovelHall'
3. Click On It

### Expected behavior

It should show novel Name with it's Cover 

### Actual behavior

It is showing only name and cover is blank

### LNReader version

1.1.12.3

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
The [all novels page](https://www.novelhall.com/all.html) on the source website doesn't have covers, how's the app supposed to show them?
