### ISSUE TITLE
[Source Request] NovelRoom

### ISSUE THREAD

**Issue by Marzl7** [LNReader/lnreader-sources#370]
### Source name

NovelRoom

### Source link

https://novelroom.net/

### Language

English

### Other details

Great App ❤️

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Added in LNReader/lnreader@d6d487101b03ee726e65fe85e4c13fc8ce56ce37
