### ISSUE TITLE
Zerobooks

### ISSUE THREAD

**Issue by ArchCelestial** [LNReader/lnreader-sources#384]
### Source name

Zerobooks 

### Source link

https://jnovels.com/

### Language

English

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by ArchCelestial** [comment]
Why was this extension rejected

**Comment by rajarsheechatterjee** [comment]
> This issue was closed because it is a duplicate of https://github.com/LNReader/lnreader-sources/issues/115.

It wasn't rejected, there's already an existing issue for it.
