### ISSUE TITLE
ReadLightNovel Chapter Not Available

### ISSUE THREAD

**Issue by Prayaero** [LNReader/lnreader-sources#390]
WebView of the site works fine but doesn't work in the app.
![Screenshot_20220918-005851_LNReader](https://user-images.githubusercontent.com/65183226/190868091-908df980-1182-47e6-bfb0-b6623d96b4f3.jpg)

**Comment by rajarsheechatterjee** [comment]
Follow the [issue template](https://github.com/LNReader/lnreader-sources/issues/new?assignees=&labels=Bug&template=report_issue.yml).
