### ISSUE TITLE
ReadLightNovel say's Chapter not Available for The Beginning After the End

### ISSUE THREAD

**Issue by Prayaero** [LNReader/lnreader-sources#391]
### Source information

ReadLightNovel

### Steps to reproduce

1. Open LNReader
2. Open ReadLightNovel
3. Open "The Beginning After the End"
4. Open Latest Chapter
5. Says Chapter not available. Report if it's available in webview.

### Expected behavior

Should open normally since Webview works and the chapters are updated.

### Actual behavior

Says Chapter not available. Report if it's available in webview.

### LNReader version

1.1.13

### Android version

Android 12; Samsung One UI 4.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Closing since all the chapters are working fine for me.

Reopen if the issue still persists.
