### ISSUE TITLE
NOBLE MTL

### ISSUE THREAD

**Issue by Vegeta2569** [LNReader/lnreader-sources#409]
### Source name

Noble Mtl

### Source link

https://noblemtl.com/

### Language

English

### Other details

it is a machine translation website for korean novels

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by K1ngfish3r** [comment]
With v1.1.14 i believe this source can be added now

**Comment by rajarsheechatterjee** [comment]
Added in LNReader/lnreader@d75ef3f444054c2dfc75fcfa7d164a9837e4e78a

**Comment by K1ngfish3r** [comment]
The chapters are appearing in reverse order so you can only start reading from the latest chapter.
Can reverse sort be added?
![Screenshot_2023-02-14-09-06-48-36_3c1c179116822eec69c21805387f0489](https://user-images.githubusercontent.com/26593485/218611811-da46171d-5660-40df-9962-32c6cf6e6960.jpg)
