### ISSUE TITLE
(NovelRingan) Can't view novel chapter 

### ISSUE THREAD

**Issue by MIRVOUS** [LNReader/lnreader-sources#410]
### Source information

NovelRingan 

### Steps to reproduce

1. Browse
2. Find 'NovelRingan' source
3. Find novel to read ex: Martial Peak
4. Start reading ch.1
5. Can't view chapter 
![Screenshot_20221018-184200](https://user-images.githubusercontent.com/45929526/196422576-b8f72152-afb6-4f69-ae2e-021594324bfa.png)

### Expected behavior

Site: 
![Screenshot_20221018-185559](https://user-images.githubusercontent.com/45929526/196422887-3249cb2e-0dd9-4aac-ae39-16fbd679695f.png)

### Actual behavior

Show nothing 

### LNReader version

1.1.13

### Android version

Android 11

### Other details

Just it 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
The chapters are loading fine for me. Is this still happening?

**Comment by X-Gorn** [comment]
Use VPN. i used Windscribe - Switzerland (Zurich Lindenhof)

**Comment by rajarsheechatterjee** [comment]
Closing as chapters are loading fine for me.

Reopen if the issue still persists.
