### ISSUE TITLE
NovelR18 and Sugar Babies can't bypass cloudflare 

### ISSUE THREAD

**Issue by SuperDuperNoob** [LNReader/lnreader-sources#411]
### Source information

NovelR18 and Sugar Babies

### Steps to reproduce

1. I click on NovelR18 and Sugar babies but it says "no results found ಥ⁠_⁠ಥ".

2. I try to open in browser, need to verify with cloudflare first but can open it ( on browser) afterward.

3. The issue is, why it still show "no result found ಥ⁠_⁠ಥ" on app? 

Shouldn't it be like Tachiyomi where when i verify cloudflare on browser, it bypass on app too?

Or it is because it's open on external browser so it's not working like that?
Or maybe there's other reason? 🤔

### Expected behavior

When you verify cloudflare on browser, it automatically verified on app too...right?

### Actual behavior

Well, it still say "no result found ｡⁠:ﾟ⁠(⁠;⁠´⁠∩⁠`⁠;⁠)ﾟ⁠:⁠｡"

Uhh, what happen? What should i do then?

### LNReader version

1.1.13

### Android version

Android 7.1.1

### Other details

Of course, i saying this because i think this app is based on tachiyomi...sorry if it's not work like that 

┻⁠━⁠┻⁠︵⁠└⁠(⁠՞⁠▽⁠՞⁠ ⁠└⁠) ~ Cheers!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> When you verify cloudflare on browser, it automatically verified on app too...right?

No

> Of course, i saying this because i think this app is based on tachiyomi...sorry if it's not work like that

Only the UI of the app is based on Tachiyomi. Both the apps are built using different technologies.

> Uhh, what happen? What should i do then?

There's no way to bypass cloudflare right now.
