### ISSUE TITLE
NovelDeGlace not working

### ISSUE THREAD

**Issue by Clewald** [LNReader/lnreader-sources#416]
### Source information

NovelDeGlace

### Steps to reproduce

Enter to NovelDeGlace extensio'

### Expected behavior

 normally it's Display novel

### Actual behavior

It displays network request failed

### LNReader version

1.1.13

### Android version

Android 12.1

### Other details

It's a french language sources

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Adam935** [comment]
Hi
I looked quickly I admit not to understand the error which causes this problem (even if I think that it is a detail which causes this problem)

I did some test it seems that the source works (**sometimes**)
as **shown in the following photos**
![Screenshot_2022-12-20-05-01-42-483_com rajarsheechatterjee LNReader](https://user-images.githubusercontent.com/50600860/208582874-bc7ccc3e-5fb0-405b-9b00-3ac7baa0301a.jpg)
![Screenshot_2022-12-20-05-01-51-977_com rajarsheechatterjee LNReader](https://user-images.githubusercontent.com/50600860/208583101-ec644a55-a67e-43ec-ae5a-28c97482aa98.jpg)

**_### BUT_**

When you change too much (too many chapters read or fast chapter changes) it can cause a problem `  Network request falled ` like u can see **on the following photos.**

![IMG_20221220_051244](https://user-images.githubusercontent.com/50600860/208583588-18c68041-d523-4709-9620-2542624ef23a.jpg)

![Screenshot_2022-12-20-05-02-00-309_com rajarsheechatterjee LNReader](https://user-images.githubusercontent.com/50600860/208583438-291e359f-ca36-4df3-801c-ab236da9a8b0.jpg)

hello I looked quickly I admit not to understand the error which causes this problem (even if I think that it is a detail which causes this problem)

I did some test it seems that the source works (sometimes)
as shown in the following photos.

But when you change too much (too many chapters read or fast chapter changes) it can cause a problem

**_HOWEVER_** 

If you empty the cache, you can read the chapters that pose a problem.
![IMG_20221220_051404](https://user-images.githubusercontent.com/50600860/208584037-60780450-9b5a-4da2-b526-205abb3b1734.jpg)

At the beginning I thought of a problem with the parses but I don't have the impression that this is the source given the situation, I admit that I have no idea here and given the low number of French source I hope that someone can help.

**Thank you in advance.**
I will continue to try to solve this problem when I have time.
