### ISSUE TITLE
[Source Request] Yushubo

### ISSUE THREAD

**Issue by seizue** [LNReader/lnreader-sources#43]
Source Name: Yushubo
Link: https://m.yushubo.com/
Language: Chinese

**Comment by BreadGenie** [comment]
Took a look and it seems like they forbid crawlers :/ 
Might need to use puppeteer but it will impact the performance and the chapters will load pretty slow

**Comment by rajarsheechatterjee** [comment]
@BreadGenie I don't think using puppeteer is possible anymore as I've moved the sources to the app.

**Comment by BreadGenie** [comment]
I've managed to make it work using user agent for now.
I'll put together a PR once it's ready
