### ISSUE TITLE
Ranobes Bug: No Results Found

### ISSUE THREAD

**Issue by Bejab** [LNReader/lnreader-sources#435]
### Source information

Ranobes (English)

### Steps to reproduce

1. I enter the ranobes extension.
2. It does not show any type of content, it simply shows: no results found.

### Expected behavior

To be able to enter the extension, to see the novels and to be able to read the chapters correctly.

### Actual behavior

It does not show content, just a text saying: No results found.

I also can't read novels that I had previously saved in my bookstore, novels from this source, just a text saying: Chapter not avaible.

### LNReader version

1.1.13

### Android version

Android 12

### Other details

![Screenshot_2022-12-28-13-24-15-942_com rajarsheechatterjee LNReader](https://user-images.githubusercontent.com/69412729/209862664-4e3dddc2-08ec-48df-be37-90742baf1945.jpg)
![Screenshot_2022-12-28-13-24-10-733_com rajarsheechatterjee LNReader](https://user-images.githubusercontent.com/69412729/209862668-6aaaf291-2afa-4da9-a7be-e9f3f71780c0.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by MM001-r** [comment]
the same problem, but in Russian ... 
![Screenshot_2023-01-23-10-44-13-13_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/71752683/213994978-cddb2486-5d2c-4c59-8c13-7fadbedf68b0.jpg)
Скорее всего проблема связана с этим .
