### ISSUE TITLE
Source not working 

### ISSUE THREAD

**Issue by SGthecoder** [LNReader/lnreader-sources#438]
### Source information

LightNovelPub

### Steps to reproduce

Go to browse
Scroll till you find LightNovelPub
Click on it
It will show no results found even if I search something there is are only no results found 

### Expected behavior

It should show all novels

### Actual behavior

It's not showing any LN

### LNReader version

1.1.13

### Android version

11

### Other details

I guess it's because of connection security check on website but please solve the problem that's my favourite extension 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Resolved in LNReader/lnreader@172145278fa47a6a0baac7fe904a0a5d05508086
