### ISSUE TITLE
Divinedaolibrary not finding new chapters for some series

### ISSUE THREAD

**Issue by Conando025** [LNReader/lnreader-sources#443]
### Source information

divinedaolibrary

### Steps to reproduce

1. Add "humanity's great sage" to you libary

### Expected behavior

It should have 200+ like on the website

### Actual behavior

It only has 105 chapters

### LNReader version

1.1.13

### Android version

Android 13

### Other details

It seems to find the newest chapters for martial peak but not for humanity's great sage
The code looks okay so not sure whats causing this without debugging it

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
The novel has 200+ chapters for me. 

Could you remove the novel from library, clear database in advanced settings and add it again?

**Comment by Conando025** [comment]
Okay so that solved it. I'm gonna close the bug now since it's not representative of the underlining issue that might be from an older version
