### ISSUE TITLE
New source

### ISSUE THREAD

**Issue by Mustafakhalifa258** [LNReader/lnreader-sources#445]
### Describe your suggested feature

This source has alot of novels available so you can try adding it
The source is 
https://archiveofourown.org/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Duplicate of #85
