### ISSUE TITLE
Not working entry

### ISSUE THREAD

**Issue by PondelekB** [LNReader/lnreader-sources#457]
### Source information

Novel hall

### Steps to reproduce

The entry The apocalypse blacksmith is throwing errors

### Expected behavior

Chapters opening

### Actual behavior

Chapters not opening

### LNReader version

1.1.12

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> The apocalypse blacksmith

I couldn't find this on the source site ^. Is the chapter loading in webview?

**Comment by rajarsheechatterjee** [comment]
Closing since the issue is stale, reopen if it still persists.
