### ISSUE TITLE
Scribblehub No longer working

### ISSUE THREAD

**Issue by CapybaraLord** [LNReader/lnreader-sources#459]
### Source information

Scribblehub

### Steps to reproduce

1. Open Browser Tab and open Scribble Hub

### Expected behavior

Displaying Novels

### Actual behavior

Nothing other than "No results found" appears in the menu

### LNReader version

1.1.14

### Android version

Android 13

### Other details

Novels from Scribble Hub That are in the library tab also no longer update.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Resolved in LNReader/lnreader@84a2561c412dabeedcfcee879671663cb441ba08
