### ISSUE TITLE
Tolong tambahkan sumber baru,untuk membaca novel romcom

### ISSUE THREAD

**Issue by Reyndesuga** [LNReader/lnreader-sources#467]
### Source name

Neosekai

### Source link

https://www.neosekaitranslations.com/

### Language

Bahasa indonesia

### Other details

Tolong tambahkan juga fitur lainnya supaya mirip dengan tachiyomi,karna aplikasi ln reader sangat membantu sekali

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
The source already exists in the app.
