### ISSUE TITLE
ReadLightNovel down

### ISSUE THREAD

**Issue by BakrAsskali** [LNReader/lnreader-sources#468]
### Source information

ReadlightNovel

### Steps to reproduce

No steps click on the source no novels show up

### Expected behavior

Novels showing up

### Actual behavior

Error no novels showing up
And saved novels no longer work

### LNReader version

Latets

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Closing since the source is working as expected. Reopen if the issue still persists.
