### ISSUE TITLE
Korean Source : 아지툰

### ISSUE THREAD

**Issue by Lucy131** [LNReader/lnreader-sources#469]
### Source name

아지툰

### Source link

https://agit554.xyz/

### Language

Korean

### Other details

Source link may changes to 555,556.
Increasing sequentially.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [x] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Closing as https://agit501.xyz/ already exists in the app. Reopen if they are separate sites.
