### ISSUE TITLE
Ranobelib duplicates of all chapters after updating to 1.1.15

### ISSUE THREAD

**Issue by Naironic** [LNReader/lnreader-sources#475]
### Source information

Ranobelib

### Steps to reproduce

1. Update any light novel from ranobelib.me in 1.1.15 version.

### Expected behavior

Searches for new chapters.

### Actual behavior

After updating it shows duplicates of all chapters as new chapters, with the same dates and titles. There were issues before when the app got confused by different translations of the same light novel, but this is not it.

### LNReader version

1.1.15

### Android version

13

### Other details

I am not sure if this error is with the app (since it appeared with an update) or with the source, so I may post it in the app repository if I get no answer in a while.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
It's expected since the url of the chapters have changed. 

You could remove the novels from library, clear database in advanced settings and add them again.
