### ISSUE TITLE
Novel Updates content text not shown

### ISSUE THREAD

**Issue by 1-minute-to-midnight** [LNReader/lnreader-sources#483]
### Source information

Novel Updates

### Steps to reproduce

1. Open Novel Updates
2. Search for "I Became A Flashing Genius At the Magic Academy"
3. open any chapter past c27

### Expected behavior

I am supposed to see the text of the novel

### Actual behavior

I just saw the title and irrelevant parts of the webpage instead.

### LNReader version

1.1.15

### Android version

Android 13

### Other details

![d51bc0a0502fd84cd1addae726c48c833947a568b576bcb3b7c496c903363754](https://user-images.githubusercontent.com/70870070/233770170-d0f9c057-cec7-40cd-8c62-a99304007eac.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.15](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by K1ngfish3r** [comment]
depending on the link that the novelupdates link is pointing to, this error can occur.

**Comment by 1-minute-to-midnight** [comment]
it seems to be because there is an embedded reader on this website for this lightnovel
