### ISSUE TITLE
Mbuh

### ISSUE THREAD

**Issue by LynnGege** [LNReader/lnreader-sources#484]
### Describe your suggested feature

Ir should worl it this

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I have updated the app to version **[1.1.15](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by LynnGege** [comment]
Like it

**Comment by K1ngfish3r** [comment]
The request is unreadable. I have no idea what this is about
