### ISSUE TITLE
A problem in a source 

### ISSUE THREAD

**Issue by yasser-lmr** [LNReader/lnreader-sources#488]
### Source information

1stKissNovel

### Steps to reproduce

1-Click on browser
2-choose the source "1stKissNovel"
3-there's no novel working even though the Web view works 

### Expected behavior

When I click on a novel there should be chapters available 

### Actual behavior

When I click on a novel there's only the picture and the resume but no chapters

### LNReader version

1.1.15

### Android version

Android 7.0

### Other details

I prefer the chapter display in version 1.1.14 more than the one in 1.1.15

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.15](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Omnisucker** [comment]
Same as you.

**Comment by Rojikku** [comment]
1. Include the  source name in the title... That title is  very useless. It defines literally any issue  in the repo.
2. The issue, effectively, appears to be that when you load the webpage it gives you a little spinning icon while it loads the chapters. So when the app parses chapters, it doesn't get chapters, it gets a spinning icon. Therefore 0 chapters display.
```
<div id="manga-chapters-holder" data-id="7568624"><i class="fas fa-spinner fa-spin fa-3x"></i></div>
```
3. I don't think the images can be fixed, I think those are intentionally being blocked.
