### ISSUE TITLE
[Source Request] Reaper Scans Novels

### ISSUE THREAD

**Issue by Subtilizer28** [LNReader/lnreader-sources#49]
Source Name: Reaper Scans Novels
Link: https://reaperscans.com/all-series/novels/
Language: English

**Comment by Subtilizer28** [comment]
Thank you for adding it!!!

**Comment by rajarsheechatterjee** [comment]
It will be there in the next update. I can share the apk with you if you want.

**Comment by BreadGenie** [comment]
@Subtilizer28 in the upcoming stable release or keep an eye on LNReader/lnreader-preview where we release the preview builds.

**Comment by Subtilizer28** [comment]
I would love to have the app. Btw is there any discord server for the app? It would be great for reporting issues and stuff in it

**Comment by BreadGenie** [comment]
https://discord.gg/gZUkVZ7u here
