### ISSUE TITLE
World concept - Heart

### ISSUE THREAD

**Issue by DraconictheIX** [LNReader/lnreader-sources#490]
### Source information

RoyalRoad

### Steps to reproduce

Chapter isnt loading

### Expected behavior

Loaded chapter

### Actual behavior

Got a link to direct me here

### LNReader version

1.1.15

### Android version

The latest one

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.15](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Rojikku** [comment]
Could not replicate.

Latest and first chapters both appear to load fine.

**Comment by rajarsheechatterjee** [comment]
Reopen if the issue still persists.
