### ISSUE TITLE
Omniscient reader viewpoint 

### ISSUE THREAD

**Issue by Dhava03** [LNReader/lnreader-sources#495]
### Source information

Morenovel

### Steps to reproduce

1No text

### Expected behavior

Hope it's fixed soon 

### Actual behavior

No text appears 

### LNReader version

1.1.15

### Android version

Android 11 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.15](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
The chapters are loading fine for me. Could be a temporary issue or the site was down.

Reopen if the issue still persists.
