### ISSUE TITLE
Issue Report 

### ISSUE THREAD

**Issue by Zaldyy112** [LNReader/lnreader-sources#502]
### Source information

SakuraNovel 

### Steps to reproduce

1. No writing appears 
2. Several bugs occurred
I really wanted to read the novel, but an unexpected error occurred.

### Expected behavior

Source fix 

### Actual behavior

Further improvements 

### LNReader version

1.1.15

### Android version

Android 11

### Other details

Please fix it asap, so I can read it again 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.15](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by K1ngfish3r** [comment]
I believe this is fixed in the preview release. Check it out here https://github.com/LNReader/lnreader-preview/releases/tag/v1.1.15.1

**Comment by rajarsheechatterjee** [comment]
Closing since the source should be fixed. Reopen if the issue still persists.
