### ISSUE TITLE
Source error

### ISSUE THREAD

**Issue by Hasan2431** [LNReader/lnreader-sources#512]
### Source information

Novelmt.com

### Steps to reproduce

Novelmt catalogue section is working as expected but when I open a novel , it's totally blank.and the same is working fine on chrome or other browser 

### Expected behavior

Novel should be visible 

### Actual behavior

It is totally blank

### LNReader version

1.1.14

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.15](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by K1ngfish3r** [comment]
Novelmt seems to work fine. Please provide novel and chapter number so we can try replicating.

**Comment by rajarsheechatterjee** [comment]
Not able to reproduce this, the source is working as expected.

You can reopen if the issue still persists
