### ISSUE TITLE
chapters is empty 

### ISSUE THREAD

**Issue by abdogabal** [LNReader/lnreader-sources#518]
### Source information

kolnovel

### Steps to reproduce

fex the source 

### Expected behavior

show the chapters

### Actual behavior

nothing appear 

### LNReader version

1.1.15

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.15](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by K1ngfish3r** [comment]
can you tell us which novel and chapter which is empty?

**Comment by abdogabal** [comment]
All chapters in  the beginning after the end

**Comment by K1ngfish3r** [comment]
![image](https://github.com/LNReader/lnreader-sources/assets/26593485/d8e040de-d3c6-475c-ac74-a0b3c710629a)
just tried out the first chapter.

can you try this build
https://github.com/K1ngfish3r/lnreader/actions/runs/5193113260
under settings > advanced > clear everything and see if the source works

**Comment by rajarsheechatterjee** [comment]
The source is working fine in the last release. Could be an issue on your end.
