### ISSUE TITLE
NovelR18: many problems

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader-sources#519]
### Source information

NovelR18

### Steps to reproduce

There are many problems to report so:

1.  Covers are not fetched in any way
![IMG_20230607_091108](https://github.com/LNReader/lnreader-sources/assets/75091899/3a24d2f6-7004-46a5-9a97-b3eff74c1dba)

2. Plots have this strange code in it at the start:
![IMG_20230607_091257](https://github.com/LNReader/lnreader-sources/assets/75091899/5747eecf-cb9e-4890-9dca-cc3dc3c48776)

3.Everytime a chapter is downloaded a toast message appear for EVERY single chapter downloaded:
![IMG_20230607_091605](https://github.com/LNReader/lnreader-sources/assets/75091899/1594c10d-761b-4ce2-9cc2-381ae6cd806c)

NOTE: despite the error message the chapter is downloaded anyway.

4.Entries of this source added to the library don't show the title at all:

https://github.com/LNReader/lnreader-sources/assets/75091899/9fb93ba8-a598-4acb-bb06-a0747ecf3224

### Expected behavior

1. covers appear
2. Clean plots with no code
3. No toast message
4. Titles of entries are showed 

### Actual behavior

see steps to reproduce

### LNReader version

1.1.15.1

### Android version

Android 8 Miui 8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.15](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by K1ngfish3r** [comment]
1.  covers appear ❌
2.  Clean plots with no code ✅
3.  No toast message ✅
4.  Titles of entries are showed ✅
