### ISSUE TITLE
random sentence 

### ISSUE THREAD

**Issue by abdogabal** [LNReader/lnreader-sources#521]
### Source information

kolnovel 

### Steps to reproduce

i opened the source and The sentences in the lnreader are not the same sentences written on the site, but are random sentences

### Expected behavior

the same sentence as site 

### Actual behavior

random sentence 

### LNReader version

1.1.15

### Android version

android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.15](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by K1ngfish3r** [comment]
This has been fixed for the next release, you may obtain a debug release here > https://github.com/K1ngfish3r/lnreader/actions/runs/5302804022

**Comment by abdogabal** [comment]
It worked great, thanks

**Comment by hamzaal7ref** [comment]
The link is expired bro 😭

**Comment by K1ngfish3r** [comment]
Try latest debug bro https://github.com/LNReader/lnreader/actions/runs/6287180526
