### ISSUE TITLE
Tanin wo yosetsukenai 

### ISSUE THREAD

**Issue by installkode** [LNReader/lnreader-sources#522]
### Source information

Sakura Novel 

### Steps to reproduce

Empty chapters

### Expected behavior

Chapter contents 

### Actual behavior

Nothing

### LNReader version

1.1.15

### Android version

Android 8.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.15](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by K1ngfish3r** [comment]
This has been fixed in the preview release you can obtain it here: https://github.com/LNReader/lnreader-preview/releases/tag/v1.1.15.1

if that didnt work you can try the debug build below:
https://github.com/LNReader/lnreader/actions/runs/5286111701
