### ISSUE TITLE
Pawread issue

### ISSUE THREAD

**Issue by Skyblu023** [LNReader/lnreader-sources#523]
### Source information

Pawread

### Steps to reproduce

1. Searched for Unsheathed on global search
2. Found it on pawread
3..Chapters unavailable on lnreader even though they're there in webview.w

### Expected behavior

The chapters should open properly.

### Actual behavior

They didn't open. Just showed an empty chapter.

### LNReader version

1.1.15

### Android version

Android 1e

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.15](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by K1ngfish3r** [comment]
They had updated their site recently after being down for awhile. Will be fixed in next update.

**Comment by K1ngfish3r** [comment]
Can you check if this debug version here fixes your issue? > https://github.com/LNReader/lnreader/actions/runs/5286111701

If this didn't fix it, let us know thanks

**Comment by Mazkoran** [comment]
> Can you check if this debug version here fixes your issue? > https://github.com/LNReader/lnreader/actions/runs/5286111701
> 
> If this didn't fix it, let us know thanks

It's fixed! Thank you so muchh
