### ISSUE TITLE
Problem in a source arnovel (arabic source)

### ISSUE THREAD

**Issue by Fadidz** [LNReader/lnreader-sources#525]
### Source information

"arnovel"

### Steps to reproduce

Information and chapters not appearing
![Screenshot_2023-06-24-23-38-11-143_com rajarsheechatterjee LNReader](https://github.com/LNReader/lnreader-sources/assets/137656915/1bc78520-14d1-4ca8-a55d-45a0ed606ef8)

### Expected behavior

Information and chapters should appear
Like
![Screenshot_2023-06-24-23-40-43-194_com rajarsheechatterjee LNReader](https://github.com/LNReader/lnreader-sources/assets/137656915/30947984-1cd5-43f3-bc66-a27af5d27b15)

### Actual behavior

Like that 
![Screenshot_2023-06-24-23-40-43-194_com rajarsheechatterjee LNReader](https://github.com/LNReader/lnreader-sources/assets/137656915/1934e1d2-7fcd-4e9b-ba74-dab5ae0dcf22)
(Another source)

### LNReader version

1.15

### Android version

11

### Other details

In all novels

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.15](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by K1ngfish3r** [comment]
can you see if this dev build works https://github.com/K1ngfish3r/lnreader/actions/runs/5369425162
lemme know if its broken (idk arabic)
