### ISSUE TITLE
Sakuranovel

### ISSUE THREAD

**Issue by Altaair07** [LNReader/lnreader-sources#526]
### Source name

Sakuranovel

### Source link

Sakuranovel.id

### Language

Indonesia

### Other details

Semua di sakura novel tidak bisa dibaca coba tolong di cek kembali

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by K1ngfish3r** [comment]
sakuranovel is available in the preview build. you can get it here https://github.com/LNReader/lnreader-preview/releases/tag/v1.1.15.1
