### ISSUE TITLE
LightNovelPub not working

### ISSUE THREAD

**Issue by Enrico-Fabbri** [LNReader/lnreader-sources#527]
### Source information

LightNovelPub

### Steps to reproduce

Search a novel on LightNovelPub using the global research and specific research.
Try to read a novel.

### Expected behavior

It should load the Light Novels

### Actual behavior

When I search a novel in the global search lnp always visualize a JSON parsing error 
![Screenshot_2023-06-28-16-20-27-07_3c1c179116822eec69c21805387f0489](https://github.com/LNReader/lnreader-sources/assets/70634071/f49e9366-d593-4e9e-823d-99add1d4adbd)
And I always get an error saying the app couldn't surpass cloudflare protection
![Screenshot_2023-06-28-16-30-02-94_3c1c179116822eec69c21805387f0489](https://github.com/LNReader/lnreader-sources/assets/70634071/0e3bef6c-3a21-46d8-8cf8-0e9dad6a59be)
It won't load all the text of the chapter
![Screenshot_2023-06-28-16-38-18-41_3c1c179116822eec69c21805387f0489.jpg](https://github.com/LNReader/lnreader-sources/assets/70634071/bfde20e9-26c8-4c0b-a1a9-369315e4b4a6)

### LNReader version

1.1.15

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.15](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by K1ngfish3r** [comment]
try this dev build: https://github.com/K1ngfish3r/lnreader/actions/runs/5403272535
it should fix
[x] lightnovelpub search
[ ] cloudflare protection? once you open the source once in webview mode and back out you should have the cookies for when you enter the source again but that is surprisingly odd
[x] open the chapter in webview and go down the chapter and accept the verification message that appears at the bottom, this lasts for around 3-4 chapters before having to do it again. this is based on my download testing

**Comment by Enrico-Fabbri** [comment]
How should I try the dev build? (I'm a noob)

**Comment by K1ngfish3r** [comment]
1. login to github
2. 
![image](https://github.com/LNReader/lnreader-sources/assets/26593485/023498f4-5464-4802-9727-9e0210f3764b)
Click on LNreader-r1 under artifacts
3. install apk on your device
4. lemme know if it works/is broken

**Comment by Enrico-Fabbri** [comment]
Ok so the thing is that now sometimes it works correctly and sometimes it doesn't.

As you can see sometimes it is unable to bypass cloudflare
![photo_1_2023-06-29_13-56-37](https://github.com/LNReader/lnreader-sources/assets/70634071/820ba302-384c-446f-89b2-911515daae20)

Sometimes it doesn't load the data
![photo_2_2023-06-29_13-56-37](https://github.com/LNReader/lnreader-sources/assets/70634071/2ff8736f-b839-4836-807f-eddd57554bf2)

And sometimes it is just stuck in this endless process
![photo_3_2023-06-29_13-56-37](https://github.com/LNReader/lnreader-sources/assets/70634071/c0aad1bf-c264-463f-a61a-6f71aceaf1e6)

**Comment by K1ngfish3r** [comment]
- [x]  due to current limitations of this app, you would most probably run into cloudflare blocking every 3 pages unless @rajarsheechatterjee can look into it
- [ ] very odd. most probably related to cloudflare but I'll try to replicate
- [x] this is tough. Based on the current logic of the source we get the chapter list page by page. Each 100 chapters is a page and there is a delay of 1s between each time the app requests a new page so it depends on how fast your internet speed is and the number of pages the novel has so a novel can have a load time of 20-30s depending on how many chapters it has (infinite mana in the apocalypse has 2307 chapters and took around 35s for me, ymmv)

**Comment by K1ngfish3r** [comment]
here's another dev build for you https://github.com/K1ngfish3r/lnreader/actions/runs/5414497422
I tried cleaning up the selectors a bit if the novel decides to go unknown and double checked the search logic. After installing go to More -> Settings -> Advanced -> Clear the stuff (5 options, read them before you use them) and try to search again.

**Comment by K1ngfish3r** [comment]
Okay I think I know what's happening. You're most likely getting cloudflare'd whilst the chapters are being loaded. (literally opening more than 5 pages if more than 500 chaps). I'll try looking into a partial load of chapters and seeing if that fixes things
