### ISSUE TITLE
NovelHall Source Blocked

### ISSUE THREAD

**Issue by adhiraj2001** [LNReader/lnreader-sources#528]
### Source information

NovelHall

### Steps to reproduce

1. Save a Novel from NovelHall source to Library
2. Try to read a chapter from that Novel using the default Reader.

### Expected behavior

Chapter contents should be readable in the default Reader.

### Actual behavior

Shows "Chapter is empty" at the top, and "Finished: Sorry, you have been blocked" at the bottom of the default Reader.
The chapter is accessible when I try to use the WebViewer.

### LNReader version

1.1.15

### Android version

Android 11

### Other details

![1](https://github.com/LNReader/lnreader-sources/assets/89650350/c9e38008-5299-4d51-b54f-87ae446e85d5)

![2](https://github.com/LNReader/lnreader-sources/assets/89650350/dfb2a325-d9a3-4a03-8003-d4398a8da383)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.15](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by K1ngfish3r** [comment]
I can confirm that novelhall has changed it's layout, I'll see if I can update the source

**Comment by rajarsheechatterjee** [comment]
Not able to reproduce this, the chapter is working as expected.

You can reopen if the issue still persists.

**Comment by adhiraj2001** [comment]
> Not able to reproduce this, the chapter is working as expected.
> 
> You can reopen if the issue still persists.

Yeah, the issue still persists for me.
I tried updating to the latest version of the app, and now the source just refuses to open the chapter by throwing a "Network request failed" error. 

(Web-view still works though)

**Comment by rajarsheechatterjee** [comment]
> Yeah, the issue still persists for me.
I tried updating to the latest version of the app, and now the source just refuses to open the chapter by throwing a "Network request failed" error.


Could you Clear Database in Advanced Settings and try to open the Novel / Chaper?

**Comment by adhiraj2001** [comment]
> Could you Clear Database in Advanced Settings and try to open the Novel / Chaper?

Seems to work now, thanks
