### ISSUE TITLE
Lost sourcecode

### ISSUE THREAD

**Issue by Orahwero** [LNReader/lnreader-sources#529]
### Describe your suggested feature

Not work sakura novel

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I have updated the app to version **[1.1.15](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by K1ngfish3r** [comment]
Please see the preview version: https://github.com/LNReader/lnreader-preview/releases/tag/v1.1.15.1

If that doesnt work, please let us know, thanks

**Comment by rajarsheechatterjee** [comment]
Closing since the source should be fixed. Reopen if the issue still persists.
