### ISSUE TITLE
[Bug] LightNovelPub source only shows the first 100 chapters

### ISSUE THREAD

**Issue by Crimson-Blade** [LNReader/lnreader-sources#53]

**Comment by Crimson-Blade** [comment]
Also on a side note, the discord invite isn't working anymore, was trying to join a while back.

**Comment by rajarsheechatterjee** [comment]
> Also on a side note, the discord invite isn't working anymore, was trying to join a while back.

The [link](https://discord.gg/QdcWN4MD63) in about section of the app should work.
