### ISSUE TITLE
Readwn 

### ISSUE THREAD

**Issue by 6ad3r** [LNReader/lnreader-sources#531]
### Source information

Readwn

### Steps to reproduce

It doesn't work 

### Expected behavior

Usually when you click chapter 1 a chapter should appear 

### Actual behavior

But it does not appear it say it is empty and report if the web has the chapter 

### LNReader version

Latest 

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.15](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Not able to reproduce this, the source is working as expected.

You can reopen if the issue still persists
