### ISSUE TITLE
Can open chapters of the novel in webview but not in app (some chapters work)

### ISSUE THREAD

**Issue by piunit1** [LNReader/lnreader-sources#535]
### Source information

Novel Updates

### Steps to reproduce

Steps to reproduce
1-Open source "Novel Updates"
2-Search "I Became A Flashing Genius At The Magic"
3-Open chapter 5.1 (just an example out of the next 10chapters 7 have the issue)

### Expected behavior

Shows the text of the novel like in webview

### Actual behavior

Shows this:

Enrollment (3)
TL Notes:
Discord
Join our discord server to get notified when new chapters are available.

Join
Patreon
Pledge to support the staff for this novel and unlock chapters ahead of time. Recieve a special role on the discord server.

Patreon
Novelupdates
Checkout the novelupdates page for this novel.

Novelupdates
Comments

### LNReader version

1.1.15

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.15](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by K1ngfish3r** [comment]
Try this dev build, https://github.com/LNReader/lnreader/actions/runs/5447078129

Login to github and download the link under artifacts

Let us know if there are issues
