### ISSUE TITLE
Ranobes.top , Ranobes.net's new domain

### ISSUE THREAD

**Issue by Suregodlu** [LNReader/lnreader-sources#540]
### Source name

Ranobes.top

### Source link

https://ranobes.top/

### Language

"English"

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Resolved in LNReader/lnreader-sources@9b5a44fe595fdb33c988f601e611a490a64a9397
