### ISSUE TITLE
Urban strengthening system 

### ISSUE THREAD

**Issue by Remielas** [LNReader/lnreader-sources#542]
### Source information

Mtlnovel

### Steps to reproduce

I can't download it even though it's there

### Expected behavior

I checked it on webversion and it works

### Actual behavior

But all it says it it's not available or something 

### LNReader version

1.1.15

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.15](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Not able to reproduce this, the novel is working as expected.

You can reopen if the issue still persists.
