### ISSUE TITLE
Chapter not available 

### ISSUE THREAD

**Issue by Aman-AGM** [LNReader/lnreader-sources#543]
### Source information

Ltnovel.com

### Steps to reproduce

Chapter number 253 is not available on app

### Expected behavior

Chapter should be shown 

### Actual behavior

Chapter is not showing

### LNReader version

1.1.15

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.15](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
The source is working as expected.

You can reopen if the issue still persists and add the novel name.
