### ISSUE TITLE
Chapters issue

### ISSUE THREAD

**Issue by Laksh285** [LNReader/lnreader-sources#545]
### Source information

Royal Road

### Steps to reproduce

Chapters are opening but there is no content there. 

### Expected behavior

There should be content.

### Actual behavior

Chapters 14 to 39 dont have any content

### LNReader version

1.1.16

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.16](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Not able to reproduce the issue.

Reopen if the issue still persists and mention the novel name.
