### ISSUE TITLE
Chapter lost

### ISSUE THREAD

**Issue by leil02** [LNReader/lnreader-sources#546]
### Source information

Sakuranovel

### Steps to reproduce

![Screenshot_2023-07-23-17-43-31-075_com rajarsheechatterjee LNReader](https://github.com/LNReader/lnreader-sources/assets/136860293/ae973e48-470c-41b1-ae6e-1b26bb0b6204)

### Expected behavior

Provide an example of the issue.

![Screenshot_2023-07-23-17-43-31-075_com rajarsheechatterjee LNReader](https://github.com/LNReader/lnreader-sources/assets/136860293/f5d55fb0-1a22-4834-a126-ed7b04e44bbe)

### Actual behavior

![Screenshot_2023-07-23-17-43-31-075_com rajarsheechatterjee LNReader](https://github.com/LNReader/lnreader-sources/assets/136860293/7a9f32e6-6c8f-418f-b5dc-20bbe6984c55)

### LNReader version

Ver "1.1.16"

### Android version

Android 11

### Other details

![Screenshot_2023-07-23-17-43-31-075_com rajarsheechatterjee LNReader](https://github.com/LNReader/lnreader-sources/assets/136860293/b87f7b0c-3ce0-4a74-972e-d9293f6e51f0)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.16](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by 1DoctorK1** [comment]
This novel also :Conquer another world with the power of minecraft!

**Comment by rajarsheechatterjee** [comment]
> This novel also :Conquer another world with the power of minecraft!

 Doesn't seem to exist on the site anymore.

Not able to reproduce the issue. Reopen and mention Novel and Chapter names if the issue still persists
