### ISSUE TITLE
Can't search anything in readwn.com

### ISSUE THREAD

**Issue by PranayR8** [LNReader/lnreader-sources#547]
### Source information

Readwn.com

### Steps to reproduce

1. Go to 'Browse'
2. Click on 'Readwn.com (ID: 68)'
3. Search up anything on the search bar - It won't work

### Expected behavior

It should search and show me the novels I want 

Example: I search up 'Siheyuan'. It should show me all of the novels with the title 'Siheyuan'

### Actual behavior

It doesn't show me the novels I search for.

Example: I search up 'Siheyuan'. It will just keep on showing me the same novels as the home page one

### LNReader version

1.1.16

### Android version

Android 12

### Other details

It might have to do with the fact that the site (Readwn.com) changed their URL to https://www.wuxiap.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.16](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Searching is working as expected. Did you submit the text after typing?


![Screenshot_1693637093](https://github.com/LNReader/lnreader-sources/assets/57822170/a54371a4-1dc8-4e54-95c0-2970b60052c6)
