### ISSUE TITLE
Empty Webview Source : SakuraNovel

### ISSUE THREAD

**Issue by AhmadNaruto** [LNReader/lnreader-sources#549]
### Source information

sakuranovel.js

### Steps to reproduce

tittel showed but when chapter click, there are noting content 

### Expected behavior

showed chapter content 

### Actual behavior

just show : 
Chapter is empty. Report on [github](https://github.com/LNReader/lnreader-sources/issues/new/choose) if it's available in webview.

### LNReader version

1.1.15

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.16](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
This has been fixed in newer release, you can download the latest release from [here](https://github.com/LNReader/lnreader/releases/tag/v1.1.17).
