### ISSUE TITLE
Konbini goto kara

### ISSUE THREAD

**Issue by Fajarian1443** [LNReader/lnreader-sources#556]
### Source information

Sakura novel

### Steps to reproduce

Tzuy tdur

### Expected behavior

Text du t-shirts

### Actual behavior

Circus tdii

### LNReader version

1.1.16

### Android version

Android 11

### Other details

Uchi icky

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.16](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Not able to reproduce it. Reopen if the issue still persists.
