### ISSUE TITLE
Source issue

### ISSUE THREAD

**Issue by MonomoySama** [LNReader/lnreader-sources#558]
### Source information

FastNovel

### Steps to reproduce

1. Opened FastNovel(English)(ID =3) source
2. Clicking on any novel

### Expected behavior

Source opening fully and search results coming out means everything should be fine

### Actual behavior

Every novel is empty in that source. I checked the webview, there were all chapters on site but in app none.

### LNReader version

1.1.16

### Android version

Android 10

### Other details

This source was fine in 1.1.15 version. I mostly used this source coz it was good and fast to update. Please fix it as fast as you can. I installed the 1.1.15 version and it was ok but in 1.1.16, no novel has chapter in this source

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.16](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by MonomoySama** [comment]
Ok so it's complete but how do it implement it in app? Because the source
still didn't change

**Comment by rajarsheechatterjee** [comment]
You'd have to wait for the next app release or you could download a dev build from [here](https://github.com/LNReader/lnreader/suites/15254145555/artifacts/871615399) (not recommended).

**Comment by MonomoySama** [comment]
Sorry for bothering you. Just a question. Is there any date or month
decided for next update 1.1.18(maybe)?  I'm asking coz there was some
problem in 1.1.17 which was fixed and will be implement in next update so.
