### ISSUE TITLE
The Strongest Husband in Ten Thousand Realms

### ISSUE THREAD

**Issue by Rakeshlenka943** [LNReader/lnreader-sources#559]
### Source information

Novelhall

### Steps to reproduce

Choose chapter 1 and it shows that error

### Expected behavior

It should have shown the novel 

### Actual behavior

It shows nothing but it shows in web view 

### LNReader version

1.1.16

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.16](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Not able to reproduce this, the chapter is loading fine.
