### ISSUE TITLE
 cloudfare verification 

### ISSUE THREAD

**Issue by Gurujiop12** [LNReader/lnreader-sources#572]
### Source information

Novelr18 

### Steps to reproduce

After going through the web view the verification keeps on going and going

### Expected behavior

I think the web view must be connected to the [browser](
/)

### Actual behavior

Hope to be fixed

### LNReader version

1.1.17 

### Android version

Android 10

### Other details

Just  cloudfare verification problem

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.16](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Not able to reproduce this, bypassing Cloudflare works fine. Could be a temporary issue.

You can reopen if the issue still persists.
