### ISSUE TITLE
Novels in source "FastNovel" doesn't show any chapters

### ISSUE THREAD

**Issue by 0JamesJoseph0** [LNReader/lnreader-sources#573]
### Source information

FastNovel

### Steps to reproduce

Open FastNovel
Select a novel (Favourited or not Favourited)

https://github.com/LNReader/lnreader-sources/assets/127913807/68374378-d7c5-4b2f-8338-0a17b3e24b3c

### Expected behavior

When opening a source, in this case "FastNovel" and selecting the novel you want whether or not you have it Favourited in the library it should show the content of the novel aka chapters.

### Actual behavior

When opening source, "FastNovel" and selecting the novel you want whether or not you have it Favourited in the library it doesn't show any chapters and when you try to update the library it doesn't update anything of the source "FastNovel"

### LNReader version

1.1.17

### Android version

Android 9

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.16](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
This has been fixed already, it should be present in the next release.
