### ISSUE TITLE
403 Forbidden error

### ISSUE THREAD

**Issue by Crazyboi007** [LNReader/lnreader-sources#574]
### Source information

NovelR18

### Steps to reproduce

1.Open NovelR18 source
2.Error is found

### Expected behavior

"Source opens"

### Actual behavior

"Shows error 403"

### LNReader version

1.1.17

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.16](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
You need to bypass Cloudflare in WebView for the source to work
