### ISSUE TITLE
Chapters don't load for certain titles for the Royal Road source

### ISSUE THREAD

**Issue by Zeznyipre** [LNReader/lnreader-sources#575]
### Source information

Royal Road

### Steps to reproduce

Open the Royal Road Source

Go to either (Heretical Fishing [Chapter 80]) or (DIE. RESPAWN. REPEAT. [Chapter 63])

The chapters won't load in LNReader, but are viewable in Webview

### Expected behavior

They should load in LNReader without having to open webview to view the contents 

### Actual behavior

Content does not load and is only viewable in Webview while giving me a message saying "Chapter is empty. Report on github if it's available in webview."

### LNReader version

1.1.17

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.16](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Both the chapters mentioned in the issue are loading fine now.

You can reopen if the issue still persists
