### ISSUE TITLE
TuNovelaLigera: Chapters not showing 

### ISSUE THREAD

**Issue by ghost** [LNReader/lnreader-sources#595]
### Source information

Tunovelaligera 

### Steps to reproduce

Chapters not showing, chapters are showing in the webview, has 1000+ but in the app are not showing:'c

### Expected behavior

Help

### Actual behavior

Please

### LNReader version

Preview last

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.17](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by K1ngfish3r** [comment]
https://github.com/K1ngfish3r/lnreader/actions/runs/6743830799
Try the above dev build
It is not a full fix yet
sign in github
download and install artifact
more > settings >  advanced > delete stuff

**Comment by christmovies** [comment]
> UPDATE: https://github.com/K1ngfish3r/lnreader/actions/runs/6745985600 Try the above dev build It is not a full fix yet sign in github download and install artifact more > settings > advanced > delete stuff

It It worked, I had given up hope, thank you very much
