### ISSUE TITLE
New source : Novel Buddy (moved from novelfull.me)

### ISSUE THREAD

**Issue by vouxe** [LNReader/lnreader-sources#600]
### Source name

Novel Buddy

### Source link

https://novelbuddy.io

### Language

English

### Other details

This was previously novelfull.me which no longer updates chapters.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Added in LNReader/lnreader@5037fa693ada7dcb415ab3c652974da895b4c9b9
