### ISSUE TITLE
لوحة مفاتيح الكيبورد 

### ISSUE THREAD

**Issue by Hamzaassila** [LNReader/lnreader-sources#601]
### Describe your suggested feature

Please

### Other details

Not working

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I have updated the app to version **[1.1.17](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by K1ngfish3r** [comment]
Please input details below
Source Name
Novel Name
Chapter Number
