### ISSUE TITLE
Chapters aren't displayed on the source FastNovel

### ISSUE THREAD

**Issue by 0JamesJoseph0** [LNReader/lnreader-sources#608]
### Source information

FastNovel

### Steps to reproduce

Open FastNovel
Select any novel
Start reading
If source display nothing then check webview
If there's captcha solve it and come back to the app

### Expected behavior

Open FastNovel
Select any novel
Start reading
If source display nothing then check webview
If there's captcha solve it and come back to the app

### Actual behavior

Open FastNovel
Select any novel
Chapters aren't displayed
checked webview, works fine
Came back to the app still no chapters

### LNReader version

1.1.17

### Android version

Android 9

### Other details

When opening a novel in FastNovel it takes a lot more time to load than before but still no chapters. There are other sources with the same issue I believe but couldn't remember which since I took a break to see if it gets fixed. Yes I tried different devices too, but they all had the same outcome

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.17](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by K1ngfish3r** [comment]
Should be fixed in v1.1.18. Do let us know how that works out for you
