### ISSUE TITLE
Ln reader is not working 

### ISSUE THREAD

**Issue by TonyRaj02** [LNReader/lnreader-sources#611]
### Source information

Ln reader 

### Steps to reproduce

![Uploading Screenshot_2023-10-09-13-29-39-30_3c1c179116822eec69c21805387f0489.jpg…]()

### Expected behavior

![Screenshot_2023-10-09-13-29-39-30_3c1c179116822eec69c21805387f0489](https://github.com/LNReader/lnreader-sources/assets/142190516/0fdf613c-68a6-4841-8765-7548ad09ad5f)

### Actual behavior

![Uploading Screenshot_2023-10-09-13-29-39-30_3c1c179116822eec69c21805387f0489.jpg…]()

### LNReader version

1.1.17

### Android version

Android 11

### Other details

![Screenshot_2023-10-09-13-29-39-30_3c1c179116822eec69c21805387f0489](https://github.com/LNReader/lnreader-sources/assets/142190516/10de2378-67fa-4f0d-8f01-5c2c7f4b4691)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.17](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Download and update to the latest release from [here](https://github.com/LNReader/lnreader/releases/tag/v1.1.18).
