### ISSUE TITLE
Missing sources

### ISSUE THREAD

**Issue by B10Reaper** [LNReader/lnreader-sources#621]
### Source information

Dragontea

### Steps to reproduce

1. Go to browse
2. Check sources
3. No source "Dragontea"
4. Enable English
5. No source
6. Uninstall/reinstall
7. No source 

### Expected behavior

The source should be available

### Actual behavior

Can not find "Dragontea"

### LNReader version

1.1.18

### Android version

10

### Other details

I added a source request but a bot closed it saying the source already existed. I didn't see it anywhere so I have no idea what's going on.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.18](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Closing this and reopening #620 since the source doesn't exist.
