### ISSUE TITLE
Foxaholic not loading chapters

### ISSUE THREAD

**Issue by Maratastic** [LNReader/lnreader-sources#635]
### Source information

Foxaholic

### Steps to reproduce

Step 1: load circumstances of a fallen lord
Step 2: pass the cloudflare check in webview to load the chapters
Step 3: try to open a chapter

### Expected behavior

Load the chapters

### Actual behavior

It gives me the notification that tehc ahpter is empty despite it not being empty on foxaholic

### LNReader version

1.1.14

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.18](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Chapters are loading as expected. Update to the latest release (v1.1.18) from [here](https://github.com/LNReader/lnreader/releases/tag/v1.1.18).
