### ISSUE TITLE
Allnovelfull image

### ISSUE THREAD

**Issue by ghost** [LNReader/lnreader-sources#645]
### Source information

Allnovelfull

### Steps to reproduce

![Screenshot_2023-11-17-16-49-04-973_com rajarsheechatterjee LNReader](https://github.com/LNReader/lnreader-sources/assets/97629848/a8c3bf5d-884c-49ad-b243-9c210c701539)

### Expected behavior

The picture looks full 

### Actual behavior

.... 

### LNReader version

1.1.18

### Android version

13

### Other details

... 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.18](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
<img width="1722" alt="Screenshot 2023-11-18 at 7 43 13 AM" src="https://github.com/LNReader/lnreader-sources/assets/57822170/d80b6597-72d7-45b5-826e-29cfee63bec9">

The entire image is not present on the source website's Popular Novels page, how is the app supposed to show them?
