### ISSUE TITLE
Add new features 

### ISSUE THREAD

**Issue by Mr-death-ji** [LNReader/lnreader-sources#650]
### Describe your suggested feature

New features.
1. name changing
2. language changing
3. Telling that some sources are missing 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I have updated the app to version **[1.1.18](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).

> name changing

Already there.

> language changing

Changing device language would change the app's language.

> Telling that some sources are missing

If the source doesn't show up in the app that means it isn't there.
