### ISSUE TITLE
Add MTL nation 

### ISSUE THREAD

**Issue by Mr-death-ji** [LNReader/lnreader-sources#653]
### Source name

Mtl nation 

### Source link

https://mtlnation.com/

### Language

English 

### Other details

Add mtn nation
Mtl nation has many novels
Mtl nation is the best for the website 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
@Mr-death-ji Stop spamming issues and read what the comment says. There's already an issue for the site.
