### ISSUE TITLE
Source Request Allnoveread

### ISSUE THREAD

**Issue by kudse** [LNReader/lnreader-sources#660]
### Source name

AllnovelRead

### Source link

https://allnovelread.com/

### Language

English

### Other details

Could you please add as a source the following site:

https://allnovelread.com/

Thanks

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
implemented in 2.0 version
