### ISSUE TITLE
syosetu cover

### ISSUE THREAD

**Issue by WilsonMinaya** [LNReader/lnreader-sources#663]
### Source information

syosetu

### Steps to reproduce

Open the extensión
![Screenshot_2023-12-08-02-25-10-659_com rajarsheechatterjee LNReader](https://github.com/LNReader/lnreader-sources/assets/152060461/46226270-6a3f-423d-8308-c58aad5a746e)

### Expected behavior

.... 

### Actual behavior

... 

### LNReader version

1.1.18

### Android version

13

### Other details

... 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.18](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Syosetu doesn't support Novel Covers. They aren't present on the website.
