### ISSUE TITLE
Chapter is empty on Novel Updates

### ISSUE THREAD

**Issue by Minibus93** [LNReader/lnreader-sources#682]
### Source information

Novel Updates

### Steps to reproduce

Search for "Drunken Thief Buys S*ave Girl"
Add it to library
Try to open any chapter
See the "chapter is empty" thing

### Expected behavior

The chapter should be readable and not appear empty

### Actual behavior

The chapter is empty error screen is showed

### LNReader version

1.1.18

### Android version

Android 13 MIUI 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.18](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by K1ngfish3r** [comment]
try this dev build: https://github.com/K1ngfish3r/lnreader/actions/runs/7489722655
1. sign in github
2. More > Settings > Advanced > Clear Database
3. If issue persists, provide screenshot

**Comment by Minibus93** [comment]
Hi, thanks for addressing the issue! 

Tested it and can confirm it now works just fine and every chapter is readable!
