### ISSUE TITLE
Local source

### ISSUE THREAD

**Issue by Randomseer** [LNReader/lnreader-sources#691]
### Source name

Local sources

### Source link

No link

### Language

Multi

### Other details

I would like the ability to read locally hosted epubs from lnreader

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
This was done in both app (current and plugins system)
