### ISSUE TITLE
"0 chapters" Novel Updates Source 

### ISSUE THREAD

**Issue by derellabfs** [LNReader/lnreader-sources#722]
### Source information

Novel Updates 

### Steps to reproduce

1. Open Novel Updates source
2. Tap on any novel available/listed on the source extension
3. The novel information page is open

### Expected behavior

The information page showing the available chapters matching the website version 

### Actual behavior

The information page showing "0 chapters" instead of the available chapters on the website version 

### LNReader version

1.1.18

### Android version

Android 11

### Other details

I already checked the website if the novels have chapters and they do, so it should be available on the app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.18](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by K1ngfish3r** [comment]
Login is now a requirement for Novel Updates
Use webview to login, then exit out the source and reenter and novels should work just fine

**Comment by derellabfs** [comment]
Thank you !! It works !!

**Comment by FatalChW** [comment]
when i login and update it works but it doesn't fetch the covers, they go blank. is it possibile to fix that? it's probably due to a different view of the page when you're logged in (not sure tho).
