### ISSUE TITLE
Linovelib: No results found when the source is clicked

### ISSUE THREAD

**Issue by alistair3149** [LNReader/lnreader-sources#723]
### Source information

Linovelib (1.0.1)

### Steps to reproduce

1. Click Linovelib in the browse tab

### Expected behavior

A grid of novels should be loaded

### Actual behavior

Blank page with the message "No results found"

### LNReader version

2.0.0

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.18](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by he0119** [comment]
It was caused by Cloudflare protection. you need to open in WebView and the navigate to rank page to bypass it.

**Comment by alistair3149** [comment]
I did that already but it is still the same.

![Screenshot_20240126-154749](https://github.com/LNReader/lnreader-sources/assets/9260542/c8fc54aa-4c73-4dae-b948-add769500d34)

**Comment by nyagami** [comment]
eh what, you are using 2.0.0? Please wait until its officail release

**Comment by alistair3149** [comment]
> eh what, you are using 2.0.0? Please wait until its officail release

It is not working on both 1.1.18 and the latest build from the CI.
On 1.1.18, it still shows the Cloudflare error after bypassing through the webview.

**Comment by he0119** [comment]
I think you have accessed the wrong page. maybe we should make open in webview to open what the plugin trying to fetch.

**Comment by alistair3149** [comment]
The rank page doesn't not trigger CloudFlare for me. The only page that triggers it is the tags page linked from home page.

![Screenshot_20240129-012021](https://github.com/LNReader/lnreader-sources/assets/9260542/2eab35b3-a712-475d-9f9a-325c8619bd7b)

However, it still doesn't let me bypass CloudFlare in the app after I have passed the challenge in WebView.

![Screenshot_20240129-012133](https://github.com/LNReader/lnreader-sources/assets/9260542/36682208-b0ff-401e-8ca8-c8fc047e9b73)

**Comment by alistair3149** [comment]
Seems like book list is working on the latest version now. However, I couldn't get the content text of the chapter:
![Screenshot_20240201-020206](https://github.com/LNReader/lnreader-sources/assets/9260542/1717da86-18e5-4bb8-a304-5900aedc79ba)

**Comment by nyagami** [comment]
Could you update the plugin and check if it works?

**Comment by alistair3149** [comment]
The content text is working now as of 1.1.1.

As for the CloudFlare bypass, I can get it working somewhat consistently by following these steps:
1. Open WebView
2. Navigate to the tags page
3. Work through the CF challenge
4. Press return button
5. Keep changing the filters until the page shows results
Though you have to do it almost every time the app launch.

Is the chapter list supposed to look like that?
![Screenshot_20240201-142358](https://github.com/LNReader/lnreader-sources/assets/9260542/792e43fd-01d8-414a-b728-0b510309ee59)

**Comment by nyagami** [comment]
- for the bypassing: yes, you can test it on your brower. You have to bypass the cloud flare for each time launching. Btw you can just press backup to browse screen and then click on the plugin. 
- for the chapter list: yes, by defaut, app shows the chapter numbers to avoid spoilers. you can change it click on this button -> display tab
![image](https://github.com/LNReader/lnreader-sources/assets/86464880/be9b6b95-2bf3-4050-8fdf-4fcbeb76bbbe)

**Comment by alistair3149** [comment]
It is all resolved now. Thank you all for the help!
