### ISSUE TITLE
Empity chapter

### ISSUE THREAD

**Issue by gideongustav78** [LNReader/lnreader-sources#734]
Dear github team, I want to express my complaint that I can't read any novels in any source. Every novel I open always contains an "empty chapter". therefore I really ask for his help. I thank you.

**Comment by K1ngfish3r** [comment]
Source name and Novel name please? I would like to reproduce your issue

**Comment by rajarsheechatterjee** [comment]
Closing since there's no response. If its still happening reopen and add the Source / Novel names.
