### ISSUE TITLE
Resource retrieval error 

### ISSUE THREAD

**Issue by Drake116** [LNReader/lnreader-sources#750]
### Source information

RoyalRoad 

### Steps to reproduce

1. Open "Apocalypse: Reborn As A Monster [A Kingdom Building Litrpg Story]"
2. Select latest chapter

### Expected behavior

Selected chapter should be displayed

### Actual behavior

Error message with Github link for reporting is displayed instead of chapter

### LNReader version

1.1.19

### Android version

HiOS 13.0.0

### Other details

Chapters are posted twice despite there being only 1 copy in WebView
Reposted chapters along with the latest chapters are not displaying properly 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by K1ngfish3r** [comment]
Unable to reproduce the issue so far, is this correct?
![image](https://github.com/LNReader/lnreader-sources/assets/26593485/0aaaca4b-9a46-4e93-9ea7-c8e4bfc61e3a)
![image](https://github.com/LNReader/lnreader-sources/assets/26593485/0fdea9eb-63a3-4805-aec4-7a6d1e84cea3)
you may try removing the novel from the library, clearing database of novels not in your library by going to More > Settings > Advanced > Clear Database and trying again

**Comment by Drake116** [comment]
The start of duplicated chapters

![Screenshot_20240208-015831](https://github.com/LNReader/lnreader-sources/assets/158810385/f99b762a-7cba-48dc-8d9a-4cbcb184e1f4)

Latest chapter

![Screenshot_20240208-015841](https://github.com/LNReader/lnreader-sources/assets/158810385/27b86525-f887-458a-9c73-110598bfcd9a)

When opened

![Screenshot_20240208-015852](https://github.com/LNReader/lnreader-sources/assets/158810385/1a04d361-cfbe-41f5-9b10-c09c1442d9a2)


I have tried to remove then add again, didn't work.
Will try again just in case
