### ISSUE TITLE
Central Novel, Portuguese source request

### ISSUE THREAD

**Issue by cabralium** [LNReader/lnreader-sources#768]
### Source name

Central Novel

### Source link

https://centralnovel.com/

### Language

Portuguese

### Other details

All other portuguese sources are, unfortunately, bad. Central Novel is the only one that have a lot of novels, don't appear to have cloudfare and isn't outdated

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by cabralium** [comment]
I dont know what that is but it sounds good. Thanks!!

**Comment by error7404** [comment]
it means that the source is available in 2.0beta

**Comment by cabralium** [comment]
Thats amazing, thank you

**Comment by nyagami** [comment]
implemented in 2.0 version
