### ISSUE TITLE
All

### ISSUE THREAD

**Issue by Ikan120605** [LNReader/lnreader-sources#779]
### Source information

SakuraNovel

### Steps to reproduce

Can,t read any ln in this extension

### Expected behavior

Can read ln

### Actual behavior

no writing appears

### LNReader version

1.1.19

### Android version

13

### Other details

Just like that thx

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by K1ngfish3r** [comment]
https://github.com/K1ngfish3r/lnreader/actions/runs/7963690173
You may try the above dev build to see if it fixes your issue
1. sign in github
2. download and install apk from artifacts

If issue persists, comment here or on the discord

**Comment by koalacodex** [comment]
> https://github.com/K1ngfish3r/lnreader/actions/runs/7963690173 You may try the above dev build to see if it fixes your issue
> 
> 1. sign in github
> 2. download and install apk from artifacts
> 
> If issue persists, comment here or on the discord

Fixed, close this & 780 & 783 as well
