### ISSUE TITLE
Otonari no tenshi

### ISSUE THREAD

**Issue by Wstermon** [LNReader/lnreader-sources#780]
### Source information

Sakura novel

### Steps to reproduce

1.tidak bisa di buka 

### Expected behavior

.

### Actual behavior

.

### LNReader version

.

### Android version

13

### Other details

Apk nya nggak bisa di buka di apk lnreader

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Wstermon** [comment]
Kagak bisa di buka LN nya kecewa

**Comment by Wstermon** [comment]
### 

> ****

**Comment by Wstermon** [comment]
Terlalu kecewa sama apk nya

**Comment by K1ngfish3r** [comment]
https://github.com/K1ngfish3r/lnreader/actions/runs/7963690173
You may try the above dev build to see if it fixes your issue
1. sign in github
2. download and install apk from artifacts

If issue persists, comment here or on the discord
