### ISSUE TITLE
Tsuki ga michibi 

### ISSUE THREAD

**Issue by Delvajr** [LNReader/lnreader-sources#783]
### Source information

ReadLighNovel

### Steps to reproduce

First step

### Expected behavior

This should happen

### Actual behavior

The happened 

### LNReader version

1.1.12

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by K1ngfish3r** [comment]
https://github.com/LNReader/lnreader/pull/962

**Comment by nyagami** [comment]
check the fixed build in https://github.com/LNReader/lnreader-sources/issues/779
