### ISSUE TITLE
Shadow Slave chapter 1445 having an empty chapter

### ISSUE THREAD

**Issue by LordRemesses** [LNReader/lnreader-sources#788]
### Source information

LNReader

### Steps to reproduce

Open LNreader 
Click Shadow slave 
Open chapter 1445

### Expected behavior

A Chapter shouldve been presented

### Actual behavior

The chapter is empty

### LNReader version

1.1.14

### Android version

Android14

### Other details

It said i should report to github if the chapter is empty

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by K1ngfish3r** [comment]
source name?

**Comment by rajarsheechatterjee** [comment]
Closing since there's no response. If its still happening reopen and add the Source name.
