### ISSUE TITLE
KolNovel  : Actions do not appear

### ISSUE THREAD

**Issue by OtakuArab** [LNReader/lnreader-sources#832]
### Source information

KolNovel

### Steps to reproduce

1- Access the source 
2- Open the source 
3- The works do not appear

### Expected behavior

Business must appear

### Actual behavior

Actions do not appear

### LNReader version

2.00

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
its domain has been changed kolnovel.net -> kolnovel.org

**Comment by nyagami** [comment]
Fixed in https://github.com/LNReader/lnreader-sources/pull/833
please update Kolnovel in app (left swipe -> click update icon)
