### ISSUE TITLE
NovelParadise : does not work

### ISSUE THREAD

**Issue by OtakuArab** [LNReader/lnreader-sources#837]
### Source information

NovelParadise

### Steps to reproduce

Going to the source shows nothing

### Expected behavior

The works must appear because the site is operational

### Actual behavior

nothing showed up 

### LNReader version

2.0

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
Follow these steps:
1. open plugin
2. open webview
3. Click continue button -> you may need to open the link in browser (like Chrome)
4. Click until you can get into the website
5. Back to app
6. refresh
![Screenshot_20240318-220803](https://github.com/LNReader/lnreader-sources/assets/86464880/3e940ed8-e8ab-4b99-a3e3-18236e6601c3)
