### ISSUE TITLE
External installation of sources

### ISSUE THREAD

**Issue by OtakuArab** [LNReader/lnreader-sources#841]
### Describe your suggested feature

There must be an external installation feature similar to the apply (Mihon , Tachiyomi , Aniyomi ) feature to install, add, and update sources

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
This is already supported in [v2.0.0](https://github.com/LNReader/lnreader/releases/tag/v2.0.0-beta.0) which is in _beta_ right now.

**Comment by OtakuArab** [comment]
> This is already supported in [v2.0.0](https://github.com/LNReader/lnreader/releases/tag/v2.0.0-beta.0) which is in _beta_ right now.

I mean installing the source application such as Tachiyomi and others as an external installation

**Comment by nyagami** [comment]
Yes all sources in v2.0.0 are external sources (plugins), you can install/uninstall/update them.
Not like Tachiyomi, LNReader doenst require Android system to install plugin as an application.

**Comment by OtakuArab** [comment]
> Yes all sources in v2.0.0 are external sources (plugins), you can install/uninstall/update them. Not like Tachiyomi, LNReader doenst require Android system to install plugin as an application.

Additional verification will be great, like Tachiyomi hiomi. You have the choice of external or internal verification انا
