### ISSUE TITLE
No Display Of Cover

### ISSUE THREAD

**Issue by Fasihurrehman-sys** [LNReader/lnreader-sources#857]
### Source information

Novel Bin

### Steps to reproduce

Step 1: Add Any Novel From Novel Bin to Library.
Step 2: It Will Not Display Any Cover

### Expected behavior

It Should Display The Cover

### Actual behavior

![WhatsApp Image 2024-03-25 at 21 02 54_c53e88a0](https://github.com/LNReader/lnreader-sources/assets/84008801/619c0f01-1e50-4c23-a67a-6fdec4b3b123)

### LNReader version

2.0.0

### Android version

13

### Other details

It Works Fine in 1.19 But Not in 2.0.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment]
It doesn't work on 1.1.19

**Comment by Fasih-ur-Rehman45** [comment]
You are right but You Can Still Use Another Picture As a thumbnail and it work in 1.1.19 but this feature is malfunctioning in 2.0.0

**Comment by Fasih-ur-Rehman45** [comment]
Uploading Screenrecorder-2024-03-26-01-37-22-264.mp4…

**Comment by Fasihurrehman-sys** [comment]
You are right but You Can Still Use Custom thumbnail and it work in 1.1.19 but this feature is malfunctioning in 2.0.0 also it works with Noveltop1 but not Novel Bin but both sites are same

**Comment by nyagami** [comment]
Because we've updated plugin sandbox, so you have to use the new app to get the novelbin update. 
You can wait for beta.1 or download the build here :https://github.com/LNReader/lnreader/actions/runs/8434693818

**Comment by Fasihurrehman-sys** [comment]
Thank you
