### ISSUE TITLE
Wuxiaworld: broken

### ISSUE THREAD

**Issue by Kingofvirgins** [LNReader/lnreader-sources#861]
### Source information

Wuxiaworld

### Steps to reproduce

Open Wuxiaworld
Click the first novel
Nothings there
Open the website
Has everything

### Expected behavior

This should jave the cover, the name of the author and the chapters

### Actual behavior

Nothing is there

### LNReader version

1.1.19

### Android version

Android S23 Ultra

### Other details

![Screenshot_20240326_211442_LNReader](https://github.com/LNReader/lnreader-sources/assets/165090610/5169c7df-e09d-4eae-9128-eb121b46a58d)
![Screenshot_20240326_211453_LNReader](https://github.com/LNReader/lnreader-sources/assets/165090610/41a9ba02-5cc5-47b9-ac17-a64dc3eefac6)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
WuxiaWorld was reimplemented in beta version.
